export const CARD_ADD_ITEM = "CARD_ADD_ITEM";
export const CARD_ADD_ITEM_SUCCESS = "CARD_ADD_ITEM_SUCCESS";
export const CARD_ADD_ITEM_FAIL = "CARD_ADD_ITEM_FAIL";

export const GET_CART_ITEM = "GET_CART_ITEM";

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
